repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format


  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--match='(?!DIPPID\\.py|pyglet_minimal\\.py|simple_sender\\.py|demo_heartbeat\\.py).*\\.py'"]
